# Generated by Django 5.2.8 on 2025-11-18 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gmail_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('programming_language', models.CharField(blank=True, max_length=100, verbose_name='Язык программирования')),
                ('experience', models.CharField(blank=True, max_length=50, verbose_name='Опыт (лет)')),
                ('experience_raw', models.TextField(blank=True, verbose_name='Опыт (сырой текст)')),
                ('used_technologies', models.TextField(blank=True, verbose_name='Стек технологий')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('soft_skills', models.TextField(blank=True, verbose_name='Soft Skills')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Владение языками')),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('waited_salary', models.CharField(blank=True, max_length=100, verbose_name='Ожидаемая ЗП')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('screening', 'Скрининг пройден'), ('interview_scheduled', 'Интервью назначено'), ('interview_passed', 'Интервью пройдено'), ('offer', 'Оффер'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время созвона')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Файл резюме')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interviews/', verbose_name='Запись интервью')),
                ('interview_transcription', models.TextField(blank=True, verbose_name='Транскрибация')),
                ('questions_answers', models.JSONField(blank=True, null=True, verbose_name='Вопросы и ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='main.position', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='main.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
