# Generated by Django 5.2.8 on 2025-11-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_position_project_alter_customuser_gmail_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience_raw',
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(null=True, verbose_name='Phone Number'),
        ),
    ]
