# Generated by Django 5.2.8 on 2025-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_candidate_experience_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, max_length=500, verbose_name='Опыт (лет)'),
        ),
    ]
