# Generated by Django 5.2.8 on 2025-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_candidate_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
