# Generated by Django 5.2.8 on 2025-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_google_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zoom_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zoom Account ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoom_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zoom Client ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zoom_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zoom Client Secret'),
        ),
    ]
