# Generated by Django 5.2.8 on 2025-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_zoom_account_id_customuser_zoom_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_bot_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Telegram бота'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Bot Token'),
        ),
    ]
