# Generated by Django 5.2.8 on 2025-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_telegram_bot_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='telegram_short_interview',
            field=models.TextField(blank=True, null=True, verbose_name='Текст телеграм интервью'),
        ),
    ]
