# Generated by Django 5.2.8 on 2025-12-10 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_candidate_telegram_short_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=255, verbose_name='Telegram Username')),
                ('interview_parameters', models.TextField(verbose_name='Параметры интервью (Промпт)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='main.candidate', verbose_name='Связанный кандидат')),
            ],
            options={
                'verbose_name': 'Сессия Telegram интервью',
                'verbose_name_plural': 'Сессии Telegram интервью',
                'indexes': [models.Index(fields=['telegram_username', 'status'], name='main_botint_telegra_34895a_idx')],
            },
        ),
    ]
