# Generated by Django 5.2.8 on 2025-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_botinterviewsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botinterviewsession',
            name='interview_parameters',
        ),
        migrations.RemoveField(
            model_name='botinterviewsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='botinterviewsession',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История переписки'),
        ),
        migrations.AddField(
            model_name='botinterviewsession',
            name='interview_mode',
            field=models.CharField(choices=[('screening', 'HR Скрининг (базовый)'), ('hard_skills', 'Техническое интервью (Hard Skills)'), ('soft_skills', 'Поведенческое интервью (Soft Skills)'), ('mixed', 'Смешанное')], default='mixed', max_length=50, verbose_name='Тип интервью'),
        ),
        migrations.AddField(
            model_name='botinterviewsession',
            name='questions_count',
            field=models.PositiveIntegerField(default=5, verbose_name='Количество вопросов'),
        ),
        migrations.AlterField(
            model_name='botinterviewsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='botinterviewsession',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20),
        ),
    ]
