# Generated by Django 5.2.8 on 2025-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_botinterviewsession_interview_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinterviewsession',
            name='interview_parameters',
            field=models.TextField(blank=True, verbose_name='Параметры интервью (Промпт)'),
        ),
    ]
